insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (1, '', 'ESTOQUE DE CARBONO', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (1, '', 'PREVENCAO DE INCENDIOS', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (1, '', 'BIODIVERSIDADE PRODUTIVA', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (1, '', 'PRODUTIVIDADE POR UNIDADE DE AREA (EFEITO POUPA TERRA)', '0.25');

insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (2, '', 'COMPETICAO COM PRODUCAO DE ALIMENTOS', '-0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (2, '', 'COMPETICAO PELA PROPRIEDADE DA TERRA', '-0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (2, '', 'PRESSAO DE DESLOCAMENTO SOBRE AREAS NAO AGRICOLAS', '-0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (2, '', 'INTERFERENCIA SOBRE A POSSE E USOS PELAS COMUNIDADES LOCAIS', '-0.25');

insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (3, '', 'AGUA PARA IRRIGACAO', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (3, '', 'USO ALEM DA DISPONIBILIDADE TEMPORARIA', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (3, '', 'COMPROMETIMENTO DO USO POR CONTAMINACAO', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (3, '', 'COMPROMETIMENTO DA CAPTACAO / ARMAZENAMENTO', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (3, '', 'AGUA PARA PROCESSAMENTE (INCLUSIVE DESSENDENTACAO)', '-0.2');

insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (4, '', 'FERTILIZANTES - CONDICIONADORES DE SOLO', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (4, '', 'FERTILIZANTES - ADUBOS QUIMICOS', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (4, '', 'PESTICIDAS - FREQUENCIA DE APLICACAO', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (4, '', 'PESTICIDAS - VARIEDADE DE INGREDIENTES ATIVOS (NAO ALTERNADOS)', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (4, '', 'PESTICIDAS - TOXICICIDADE', '-0.3');

insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (5, '', 'USO DE MATERIAS-PRIMAS - MATERIAS-PRIMAS BASICAS', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (5, '', 'USO DE MATERIAS-PRIMAS - ADITIVOS AGROINDUSTRIAIS', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (5, '', 'USO DE MATERIAS-PRIMAS - MATERIAS-PRIMAS PARA PROCESSO', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (5, '', 'USO DE INSUMOS - RACOES E SUPLEMENTOS', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (5, '', 'USO DE INSUMOS - FENO, SILAGEM, FORRAGEM', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (5, '', 'USO DE INSUMOS - PRODUTOS VETERINARIOS', '-0.3');

insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (6, '', 'FONTES DE ENERGIA - BIO-COMBUSTIVEIS', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (6, '', 'FONTES DE ENERGIA - BIOMASSA (LENHA, BAGACOS, ETC)', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (6, '', 'FONTES DE ENERGIA - COMBUSTIVEIS FOSSEIS', '-0.3');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (6, '', 'FONTES DE ENERGIA - ELETRICIDADE', '-0.5');

insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (7, '', 'AUTONOMIA MATERIAL E ENERGETICA - (CO)GERACAO MOTRIZ OU ELETRICA (SOLAR, EOLICA, HIDRO, BIOGAS)', '0.3');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (7, '', 'AUTONOMIA MATERIAL E ENERGETICA - APROVEITAMENTO TERMICO (CONSUMO ENERGETICO EVITADO)', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (7, '', 'AUTONOMIA MATERIAL E ENERGETICA - CONTROLE BIOLOGICO | MANEJO ECOLOGICO DE PRAGAS E DOENCAS', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (7, '', 'AUTONOMIA MATERIAL E ENERGETICA - ADUBO VERDE | FIXACAO BIOLOGICA N | INOCULACAO MICORRIZICA', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (7, '', 'AUTONOMIA MATERIAL E ENERGETICA - ADUBO ORGANICO | ESTERCO | ESTRUME | COMPOSTAGEM | FORMULADOS ORGANICOMINERAIS', '0.25');

insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (8, '', 'EMISSOES A ATMOSFERA - ODORES', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (8, '', 'EMISSOES A ATMOSFERA - RUIDOS', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (8, '', 'EMISSOES A ATMOSFERA - GASES DE EFEITO ESTUFA', '-0.4');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (8, '', 'EMISSOES A ATMOSFERA - MATERIAL PARTICULADO | FUMACA', '-0.4');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (9, '', 'QUALIDADE DO SOLO - EROSAO', '-0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (9, '', 'QUALIDADE DO SOLO - COMPACTACAO', '-0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (9, '', 'QUALIDADE DO SOLO - PERDA DE NUTRIENTES', '-0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (9, '', 'QUALIDADE DO SOLO - PERDA DE MATERIA ORGANICA', '-0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (10, '', 'QUALIDADE DA AGUA - TURBIDEZ', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (10, '', 'QUALIDADE DA AGUA - ASSOREAMENTO DE CORPOS DAGUA', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (10, '', 'QUALIDADE DA AGUA - ESPUMAS | OLEOS | RESIDUOS SOLIDOS', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (10, '', 'QUALIDADE DA AGUA - CARGA ORGANICA (EFLUENTES, ESGOTOS, ESTERCOS, ETC)', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (10, '', 'QUALIDADE DA AGUA - EXPOSICAO A CONTAMINACAO DIRETA | INDIRETA POR AGROTOXICOS', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (11, '', 'CONSERVACAO DA BIODIVERSIDADE - FAUNA SILVESTRE', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (11, '', 'CONSERVACAO DA BIODIVERSIDADE - VEGETACAO NATIVA', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (11, '', 'CONSERVACAO DA BIODIVERSIDADE - ESPECIES | VARIEDADES TRADICIONAIS (CABOCLAS)', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (11, '', 'RECUPERACAO AMBIENTAL - RESERVA LEGAL', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (11, '', 'RECUPERACAO AMBIENTAL - AREAS DE PRESERVACAO PERMANENTE', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (11, '', 'RECUPERACAO AMBIENTAL - SOLOS DEGRADADOS', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (11, '', 'RECUPERACAO AMBIENTAL - ECOSSISTEMAS DEGRADADOS', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (12, '', 'QUALIDADE DO PRODUTO - PROCEDIMENTOS DE POS-COLHEITA', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (12, '', 'QUALIDADE DO PRODUTO - DISPONIBILIDADE DE FONTES DE INSUMOS', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (12, '', 'QUALIDADE DO PRODUTO - IDONEIDADE DOS FORNECEDORES DE INSUMOS', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (12, '', 'QUALIDADE DO PRODUTO - REDUCAO DE RESIDUOS QUIMICOS', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (12, '', 'QUALIDADE DO PRODUTO - REDUCAO DE CONTAMINANTES BIOLOGICOS', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (13, '', 'ENGAJAMENTO EM MOVIMENTOS SOCIAIS', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (13, '', 'INTEGRACAO CULTURAL ENTRE OS COLABORADORES E FAMILIARES', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (13, '', 'CAPTACAO DE DEMANDAS DA COMUNIDADE', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (13, '', 'PROJETOS DE EXTENSAO COMUNITARIA | EDUCACAO AMBIENTAL', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (13, '', 'PROGRAMAS DE TRANSFERENCIA DE CONHECIMENTOS E TECNOLOGIAS', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (13, '', 'CONSERVACAO DO PATRIMONIO HISTORICO | ARTISTICO | CULTURAL', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (14, '', 'ACOES QUE MINIMIZEM O SOFRIMENTO, O ESTRESSE E A DOR', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (14, '', 'CONDUTA ETICA DE MANEJO, DESCARTE E PRE-ABATE | ABATE', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (14, '', 'CONDICOES P/ EXPRESSAR COMPORTAMENTOS NATURAIS DA ESPECIE', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (14, '', 'ACESSO A AGUA, ALIMENTO E SUPLEMENTOS DE QUALIDADE', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (14, '', 'CONFORTO TERMICO E SALUBRIDADE DOS AMBIENTES DE MANEJO', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (14, '', 'SEGURANCA E MANEJO SANITARIO PREVENTIVO', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (14, '', 'LOTACAO ADEQUADA NAS INSTALACOES E AREAS EXTERNAS', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (15, '', 'NIVEL DE CAPACITACAO - BASICO', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (15, '', 'NIVEL DE CAPACITACAO - TECNICO', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (15, '', 'NIVEL DE CAPACITACAO - SUPERIOR', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (15, '', 'TIPO DE CAPACITACAO - EDUCACAO FORMAL', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (15, '', 'TIPO DE CAPACITACAO - ESPECIALIZACAO', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (15, '', 'TIPO DE CAPACITACAO - LOCAL DE CURTA DURACAO', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (16, '', 'CONDICAO DE CONTRATACAO - PERMANENTE', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (16, '', 'CONDICAO DE CONTRATACAO - PARCEIRO | MEEIRO', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (16, '', 'QUALIFICACAO REQUERIDA PARA O TRABALHO - BRACAL', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (16, '', 'QUALIFICACAO REQUERIDA PARA O TRABALHO - TECNICO SUPERIOR', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (16, '', 'CONDICAO DE CONTRATACAO - TEMPORARIO', '0.05');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (16, '', 'CONDICAO DE CONTRATACAO - FAMILIAR', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (16, '', 'QUALIFICACAO REQUERIDA PARA O TRABALHO - TECNICO MEDIO', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (16, '', 'QUALIFICACAO REQUERIDA PARA O TRABALHO - BRACAL ESPECIALIZADO', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (17, '', 'LEGISLACAO TRABALHISTA - REGISTRO', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (17, '', 'LEGISLACAO TRABALHISTA - PREVENCAO DE JORNADA > 44HS', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (17, '', 'LEGISLACAO TRABALHISTA - CONTRIBUICAO PREVIDENCIARIA', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (17, '', 'LEGISLACAO TRABALHISTA - PREVENCAO DO TRABALHO INFANTIL', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (17, '', 'BENEFICIOS TRABALHISTAS - AUXILIO MORADIA', '0.05');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (17, '', 'BENEFICIOS TRABALHISTAS - AUXILIO TRANSPORTE', '0.05');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (17, '', 'BENEFICIOS TRABALHISTAS - AUXILIO ALIMENTACAO', '0.05');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (17, '', 'BENEFICIOS TRABALHISTAS - AUXILIO SAUDE (COMPLEMENTAR)', '0.05');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (18, '', 'EQUIDADE ETNICA - RESPEITO MUTUO E VALORIZACAO CULTURAL', '0.125');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (18, '', 'EQUIDADE ETNICA - EQUIDADE DE OPORTUNIDADES ENTRE ETNIAS', '0.125');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (18, '', 'EQUIDADE DE GENEROS - EMANCIPACAO E RECONHECIMENTO DAS ESCOLHAS DAS MULHERES', '0.125');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (18, '', 'EQUIDADE DE GERACOES - RECOMPENSA EQUITATIVA DAS ATIVIDADES PRODUTIVAS DOS JOVENS', '0.125');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (18, '', 'EQUIDADE DE GENEROS - RECOMPENSA EQUITATIVA DAS ATIVIDADES PRODUTIVAS DAS MULHERES', '0.125');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (18, '', 'EQUIDADE DE GERACOES - EMANCIPACAO E RECONHECIMENTO DAS ESCOLHAS DOS JOVENS E IDOSOS', '0.125');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (18, '', 'EQUIDADE DE GENEROS - OPORTUNIDADE DE ENVOLVIMENTO E VALORIZACAO DA PARTICIPACAO DAS MULHERES', '0.125');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (18, '', 'EQUIDADE DE GERACOES - OPORTUNIDADE DE ENVOLVIMENTO E VALORIZACAO DA PARTICIPACAO DOS JOVENS E IDOSOS', '0.125');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (19, '', 'ATRIBUTOS DE RENDA - MONTANTE', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (19, '', 'ATRIBUTOS DE RENDA - DIVERSIDADE DE FONTES DE RENDA', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (19, '', 'ATRIBUTOS DE RENDA - SEGURANCA (GARANTIA DE OBTENCAO)', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (19, '', 'ATRIBUTOS DE RENDA - ESTABILIDADE (REDUCAO DA SAZONALIDADE)', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (19, '', 'ATRIBUTOS DE RENDA - DISTRIBUICAO (REMUNERACOES E BENEFICIOS)', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (20, '', 'VALORIZACAO DA PROPRIEDADE - PRECOS DE PRODUTOS E SERVICOS', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (20, '', 'VALORIZACAO DA PROPRIEDADE - CONFORMIDADE COM LEGISLACAO', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (20, '', 'VALORIZACAO DA PROPRIEDADE - INFRA-ESTRUTURA | POLITICA TRIBUTARIA ETC', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (20, '', 'VALORIZACAO DA PROPRIEDADE - INVESTIMENTO EM BENFEITORIAS', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (20, '', 'VALORIZACAO DA PROPRIEDADE - CONSERVACAO DOS RECURSOS NATURAIS', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (21, '', 'EXPOSICAO A PERICULOSIDADES E FATORES DE INSALUBRIDADES - RUIDO', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (21, '', 'EXPOSICAO A PERICULOSIDADES E FATORES DE INSALUBRIDADES - VIBRACAO', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (21, '', 'EXPOSICAO A PERICULOSIDADES E FATORES DE INSALUBRIDADES - AGENTES BIOLOGICOS', '-0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (21, '', 'EXPOSICAO A PERICULOSIDADES E FATORES DE INSALUBRIDADES - AGENTES QUIMICOS', '-0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (21, '', 'EXPOSICAO A PERICULOSIDADES E FATORES DE INSALUBRIDADES - PERICULOSIDADE', '-0.3');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (21, '', 'EXPOSICAO A PERICULOSIDADES E FATORES DE INSALUBRIDADES - CALOR | FRIO | UMIDADE', '-0.05');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (21, '', 'EXPOSICAO A PERICULOSIDADES E FATORES DE INSALUBRIDADES - ACIDENTES ERGONOMICOS (QUEDAS, MAQUINAS)', '-0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (22, '', 'SEGURANCA ALIMENTAR - GARANTIA DA PRODUCAO', '0.3');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (22, '', 'SEGURANCA ALIMENTAR - QUANTIDADE DE ALIMENTO', '0.3');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (22, '', 'SEGURANCA ALIMENTAR - QUALIDADE NUTRICIONAL DO ALIMENTO', '0.4');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (23, '', 'DEDICACAO DO RESPONSAVEL - CAPACITACAO DIRIGIDA A ATIVIDADE', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (23, '', 'DEDICACAO DO RESPONSAVEL - HORAS DE PERMANENCIA NO ESTABELECIMENTO', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (23, '', 'DEDICACAO DO RESPONSAVEL - ENGAJAMENTO FAMILIAR', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (23, '', 'DEDICACAO DO RESPONSAVEL - USO DE SISTEMA CONTABIL', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (23, '', 'DEDICACAO DO RESPONSAVEL - MODELO FORMAL DE PLANEJAMENTO', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (23, '', 'DEDICACAO DO RESPONSAVEL - SISTEMA DE CERTIFICACAO | ROTULAGEM', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (24, '', 'COMERCIALIZACAO - COOPERACAO COM OUTROS PRODUTORES LOCAIS', '0.1');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (24, '', 'COMERCIALIZACAO - TRANSPORTE PROPRIO', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (24, '', 'COMERCIALIZACAO - ARMAZENAMENTO LOCAL', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (24, '', 'COMERCIALIZACAO - PROCESSAMENTO LOCAL', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (24, '', 'COMERCIALIZACAO - PROPAGANDA | MARCA PROPRIA', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (24, '', 'COMERCIALIZACAO - VENDA DIRETA | ANTECIPADA | COOPERADA', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (24, '', 'COMERCIALIZACAO - ENCADEAMENTO COM PRODUTOS | ATIVIDADES | SERVICOS ANTERIORES', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (25, '', 'TRATAMENTO DE RESIDUOS DOMESTICOS - COLETA SELETIVA', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (25, '', 'TRATAMENTO DE RESIDUOS DA PRODUCAO - REAPROVEITAMENTO', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (25, '', 'TRATAMENTO DE RESIDUOS DOMESTICOS - DISPOSICAO SANITARIA', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (25, '', 'TRATAMENTO DE RESIDUOS DOMESTICOS - COMPOSTAGEM | REAPROVEITAMENTO', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (25, '', 'TRATAMENTO DE RESIDUOS DA PRODUCAO - DESTINACAO OU TRATAMENTO FINAL', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (26, '', 'GESTAO DE INSUMOS QUIMICOS - ARMAZENAMENTO', '0.2');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (26, '', 'GESTAO DE INSUMOS QUIMICOS - REGISTRO DE TRATAMENTOS', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (26, '', 'GESTAO DE INSUMOS QUIMICOS - DISPOSICAO FINAL ADEQUADA DE RECIPIENTES E EMBALAGENS', '0.15');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (26, '', 'GESTAO DE INSUMOS QUIMICOS - UTILIZACAO DE EQUIPAMENTOS DE PROTECAO INDIVIDUAL', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (26, '', 'GESTAO DE INSUMOS QUIMICOS - CALIBRACAO E VERIFICACAO DE EQUIPAMENTOS DE APLICACAO', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (27, '', 'ALCANCE INSTITUCIONAL - FILIACAO TECNOLOGICA NOMINAL', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (27, '', 'ALCANCE INSTITUCIONAL - ASSOCIATIVISMO | COOPERATIVISMO', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (27, '', 'ALCANCE INSTITUCIONAL - UTILIZACAO DE ASSISTENCIA TECNICA', '0.25');
insert into _referencia.dbindicadorref_socamb (idcriterio,sigla,nome,valorimportancia ) VALUES (27, '', 'ALCANCE INSTITUCIONAL - UTILIZACAO DE ASSESSORIA LEGAL | VISTORIA', '0.25');