CREATE TABLE TBN_CRITERIO_REF_SOCAMB (
  COD_CRITERIO_REF_SOCAMB INTEGER NOT NULL,
  COD_DIMENSAO_ASPECTO_SOCAMB INTEGER NOT NULL,
  DSC_NOME VARCHAR(100) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
  VLR_IMPORTANCIA NUMERIC(5, 3) DEFAULT 0.1);


ALTER TABLE TBN_CRITERIO_REF_SOCAMB ADD PRIMARY KEY (COD_CRITERIO_REF_SOCAMB);

ALTER TABLE TBN_CRITERIO_REF_SOCAMB ADD CONSTRAINT FK_TCRSA_TDA_SOCAMB FOREIGN KEY (COD_DIMENSAO_ASPECTO_SOCAMB) REFERENCES TBN_DIMENSAO_ASPECTO_SOCAMB(COD_DIMENSAO_ASPECTO_SOCAMB) ON DELETE CASCADE ON UPDATE CASCADE;

SET TERM ^ ;

CREATE TRIGGER TRG_COD_CRITERIO_REF_SOCAMB FOR TBN_CRITERIO_REF_SOCAMB
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.COD_CRITERIO_REF_SOCAMB IS NULL) THEN
      NEW.COD_CRITERIO_REF_SOCAMB = GEN_ID(SEQ_COD_CRITERIO_REF_SOCAMB, 1);
END^

SET TERM ; ^



/* Data for the `TBN_CRITERIO_REF_SOCAMB` table  (Records 1 - 27) */

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (1, 1, 'MUDANCA NO USO DIRETO DA TERRA', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (2, 1, 'MUDANCA NO USO INDIRETO DA TERRA', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (3, 1, 'CONSUMO DE AGUA', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (4, 1, 'USO DE INSUMOS AGRICOLAS', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (5, 1, 'USO DE INSUMOS VETERINARIOS E MATERIAS-PRIMAS', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (6, 1, 'CONSUMO DE ENERGIA', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (7, 1, 'GERACAO PROPRIA, APROVEITAMENTO, REUSO E AUTONOMIA', 0.025);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (8, 2, 'EMISSOES A ATMOSFERA', 0.02);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (9, 2, 'QUALIDADE DO SOLO', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (10, 2, 'QUALIDADE DA AGUA', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (11, 2, 'CONSERVACAO DA BIODIVERSIDADE E RECUPERACAO AMBIENTAL', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (12, 3, 'QUALIDADE DO PRODUTO', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (13, 3, 'CAPITAL SOCIAL', 0.02);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (14, 3, 'BEM-ESTAR E SAUDE ANIMAL', 0.02);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (15, 4, 'CAPACITACAO', 0.02);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (16, 4, 'QUALIFICACAO E OFERTA DE TRABALHO', 0.02);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (17, 4, 'QUALIDADE DO EMPREGO / OCUPACAO', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (18, 4, 'OPORTUNIDADE, EMANCIPACAO E RECOMPENSA EQUITATIVA ENTRE GENEROS, GERACOES E ETNIAS', 0.02);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (19, 5, 'GERACAO DE RENDA', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (20, 5, 'VALOR DA PROPRIEDADE', 0.02);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (21, 6, 'SEGURANCA E SAUDE OCUPACIONAL', 0.025);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (22, 6, 'SEGURANCA ALIMENTAR', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (23, 7, 'DEDICACAO E PERFIL DO RESPONSAVEL', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (24, 7, 'CONDICAO DE COMERCIALIZACAO', 0.05);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (25, 7, 'DISPOSICAO DE RESIDUOS', 0.02);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (26, 7, 'GESTAO DE INSUMOS QUIMICOS', 0.02);

INSERT INTO TBN_CRITERIO_REF_SOCAMB (COD_CRITERIO_REF_SOCAMB, COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME, VLR_IMPORTANCIA)
VALUES (27, 7, 'RELACIONAMENTO INSTITUCIONAL', 0.02);

COMMIT WORK;

