/* Data for the `TBN_DIMENSAO_ASPECTO_SOCAMB` table  (Records 1 - 7) */

INSERT INTO TBN_DIMENSAO_ASPECTO_SOCAMB (COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME)
VALUES (1, 'Impactos Ecológicos - Eficiência Tecnológica');

INSERT INTO TBN_DIMENSAO_ASPECTO_SOCAMB (COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME)
VALUES (2, 'Impactos Ecológicos - Qualidade Ambiental');

INSERT INTO TBN_DIMENSAO_ASPECTO_SOCAMB (COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME)
VALUES (3, 'Impactos Socio-Ambientais - Respeito ao Consumidor');

INSERT INTO TBN_DIMENSAO_ASPECTO_SOCAMB (COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME)
VALUES (4, 'Impactos Socio-Ambientais - Trabalho / Emprego');

INSERT INTO TBN_DIMENSAO_ASPECTO_SOCAMB (COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME)
VALUES (5, 'Impactos Socio-Ambientais - Renda');

INSERT INTO TBN_DIMENSAO_ASPECTO_SOCAMB (COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME)
VALUES (6, 'Impactos Socio-Ambientais - Saúde');

INSERT INTO TBN_DIMENSAO_ASPECTO_SOCAMB (COD_DIMENSAO_ASPECTO_SOCAMB, DSC_NOME)
VALUES (7, 'Impactos Socio-Ambientais - Gestão e Administração');

COMMIT WORK;

